name: go_mep_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: any
  shared_preferences: any
  cupertino_icons: any
  shimmer: any
  bloc: any
  flutter_bloc: any
  http: any
  http_parser: any
  image_gallery_saver_plus: any
  webview_flutter: any
  flutter_datetime_picker_plus: any
  rxdart: any
  keyboard_actions: any
  auto_size_text_plus: any
  badges: any
  fluttertoast: any
  intl: any
  url_launcher: any
  cached_network_image: any
  flutter_animate: ^4.5.2
  fl_chart: ^0.65.0
  image_picker: 1.1.2
  permission_handler: 11.4.0
  device_info_plus: 11.3.3
  path_provider: ^2.1.5
  flutter_image_compress: ^2.3.0
  card_swiper: 3.0.1
  dio: ^5.8.0+1
  provider: ^6.1.5
  overlay_support: ^2.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  image: ^4.2.0
  pointycastle: ^4.0.0
  basic_utils: ^5.8.2
  fast_rsa: ^3.6.0
  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.0.9
  flutter_svg: ^2.2.1
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  drift: ^2.16.0
  drift_sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/figma/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
